### ISSUE TITLE
Consideration of testing frameworks

### ISSUE THREAD

**Issue by cbondurant** [Scarly-Cat/lamia#13]
There are quite a few different test frameworks out there. 
The one that I have experience with is [pytest](`https://docs.pytest.org/en/latest/`), however I don't have a strong opinion at this time.

After all, there is also [unittest](https://docs.python.org/3/library/unittest.html) which is part of the standard lib, allowing us to keep the dependencies from getting too big.(Our requires.txt is 37 lines long on the email branch, I think there's some dead dependencies on main) 

I know in #1 there was discussion that the email system needed tests of some kind. 
Either a testing framework can be added in with the email branch, or it can be merged with master and pulled into the existing branch before tests are written.

Either way, what framework do we want to use?

**Comment by Scarly-Cat** [comment]
Oh carp, I should have said something last night (tho, i was zoned at the time....) but, I pretty much went to pytest on this on the main branch. You can see what I have right now under the "/tests" folder.

I like pytest bc it has cuts down on the mental overhead of writing tests by having strong introspection. Testing should be a bit magical, since it makes it easier to keep up when them in a FOSS project by taking the edge off

**Comment by Scarly-Cat** [comment]
(Just tamed the requirements files and broke out dev and production requirements, tbh.)

**Comment by cbondurant** [comment]
Closing this because I think discussion is pretty well clear.
