### ISSUE TITLE
We could really use a lint for code formatting

### ISSUE THREAD

**Issue by Scarly-Cat** [Scarly-Cat/lamia#4]
@cbondurant if you get something setup then i'm good with it

put it under 

scripts/

which seems to be the starlette convention

**Comment by cbondurant** [comment]
There are two options I can think of generally: 

Using pylint as a soft guide, (try and keep above some general rating across the codebase, with some agreed upon presets)
Using yapf as a hard guideline: (a precommit hook that is hard-coded into the repo)

We could also use both at once, as there is a decent amount of area where the two do not overlap. 

Im going to test some stuff and push it to a yapf branch before anything goes to master.

**Comment by cbondurant** [comment]
A very basic linting script was made in branch yapf-inital (only now as I am writing this am I realizing I spelled initial wrong...) 

The code was modified using the guidelines of the script so that we could get a sense for how it would affect the codebase. 

Intended usage is that the script should be run before any commits, or at minimum, should be run before any pull requests. With a minimum required pylint score before code would be accepted.
